### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by lucenera** [Magisk-Modules-Repo/swaptorpedo#3]
What state is the project in? You're still working on it. is compatible with LineageOS 15.1 and Magisk v18.2 on Samsung Galaxy S9?

**Comment by EarlyMon** [comment]
If it's not compatible, it will do harm - it's a non-permanent systemless change, and is only invoked at boot time. If it doesn't work, you can uninstall it without side effects.

Please let me know how it goes for you. 

I consider it an active module but I have been away, spending up to 20 hours/day at an ICU for a loved one, so my time is limited. When I get a day off, whenever that happens, I will be able to provide updates as necessary. 

If it doesn't work out right now, I recommend using Kernel Adiutor as a good alternative. Like my solution, it's not able to provide 100% coverage but between the two tools, we seem to have covered everything.

Hope that helps!

**Comment by lucenera** [comment]
I tried it and at the moment it works just fine. I hope that, whatever problem you have, I can solve it as soon as possible and in the best way. Thank you.
